version: "3.9"

services:
  nginx:
    build:
      context: ./nginx
    image: f5-nginx
    container_name: nginx
    ports:
      - "8080:8080"
      - "8081:8081"
      - "443:443"

  tests:
    build:
      context: ./tests
    image: f5-nginx-tests
    depends_on:
      - nginx
